"""
GUI Builder für Migration Tool
Baut alle UI-Komponenten auf
"""

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout,
    QGroupBox, QLineEdit, QLabel, QPushButton, QTextEdit, QProgressBar,
    QComboBox, QCheckBox
)
from PyQt6.QtGui import QFont


def create_input(label, default_value, password=False, tooltip=""):
    """Erstelle Label + Input Feld"""
    layout = QHBoxLayout()
    lbl = QLabel(label)
    lbl.setMinimumWidth(80)
    input_field = QLineEdit(default_value)
    
    if tooltip:
        input_field.setToolTip(tooltip)
    
    if password:
        input_field.setEchoMode(QLineEdit.EchoMode.Password)
        
        # Toggle Button für Passwort anzeigen
        toggle_btn = QPushButton("👁")
        toggle_btn.setMaximumWidth(40)
        toggle_btn.setCheckable(True)
        toggle_btn.setToolTip("Passwort anzeigen/verstecken")
        toggle_btn.clicked.connect(lambda checked: toggle_password_visibility(input_field, checked))
        
        layout.addWidget(lbl)
        layout.addWidget(input_field)
        layout.addWidget(toggle_btn)
    else:
        layout.addWidget(lbl)
        layout.addWidget(input_field)
        
    return (layout, input_field)


def toggle_password_visibility(input_field, show):
    """Schalte Passwort-Sichtbarkeit um"""
    if show:
        input_field.setEchoMode(QLineEdit.EchoMode.Normal)
    else:
        input_field.setEchoMode(QLineEdit.EchoMode.Password)


def build_database_section():
    """Baue Datenbankverbindungs-Sektion"""
    db_group = QGroupBox("Datenbankverbindungen")
    db_layout = QVBoxLayout()
    
    # MSSQL
    mssql_layout = QVBoxLayout()
    mssql_label = QLabel("MSSQL Server:")
    mssql_label.setFont(QFont("Arial", 10, QFont.Weight.Bold))
    mssql_layout.addWidget(mssql_label)
    
    mssql_server = create_input("Server:", "")
    mssql_port = create_input("Port (optional):", "", tooltip="Standardport: 1433")
    mssql_database = create_input("Database:", "")
    mssql_user = create_input("User:", "")
    mssql_password = create_input("Password:", "", password=True)
    
    mssql_layout.addLayout(mssql_server[0])
    mssql_layout.addLayout(mssql_port[0])
    mssql_layout.addLayout(mssql_database[0])
    mssql_layout.addLayout(mssql_user[0])
    mssql_layout.addLayout(mssql_password[0])
    
    # PostgreSQL
    pg_layout = QVBoxLayout()
    pg_label = QLabel("PostgreSQL:")
    pg_label.setFont(QFont("Arial", 10, QFont.Weight.Bold))
    pg_layout.addWidget(pg_label)
    
    pg_host = create_input("Host:", "")
    pg_port = create_input("Port (optional):", "", tooltip="Standardport: 5432")
    pg_database = create_input("Database:", "")
    pg_user = create_input("User:", "")
    pg_password = create_input("Password:", "", password=True)
    
    pg_layout.addLayout(pg_host[0])
    pg_layout.addLayout(pg_port[0])
    pg_layout.addLayout(pg_database[0])
    pg_layout.addLayout(pg_user[0])
    pg_layout.addLayout(pg_password[0])
    
    # Kombiniere MSSQL und PostgreSQL nebeneinander
    db_row = QHBoxLayout()
    db_row.addLayout(mssql_layout)
    db_row.addLayout(pg_layout)
    
    db_layout.addLayout(db_row)
    
    # Log-Level Einstellung
    options_layout = QHBoxLayout()
    log_level_label = QLabel("Log-Level:")
    log_level_label.setMinimumWidth(80)
    log_level_combo = QComboBox()
    log_level_combo.addItems(["DEBUG", "INFO", "WARNING", "ERROR"])
    log_level_combo.setCurrentText("DEBUG")
    log_level_combo.setToolTip("Wählen Sie das Logging-Level:\nDEBUG = Alle Meldungen\nINFO = Wichtige Meldungen\nWARNING = Nur Warnungen und Fehler\nERROR = Nur Fehler")
    options_layout.addWidget(log_level_label)
    options_layout.addWidget(log_level_combo)
    
    # Checkbox für Datenmigrationen
    migrate_data_checkbox = QCheckBox("Daten migrieren")
    migrate_data_checkbox.setChecked(True)
    migrate_data_checkbox.setToolTip("Wenn aktiviert: Tabelleninhalt wird migriert\nWenn deaktiviert: Nur die Tabellenstruktur")
    options_layout.addWidget(migrate_data_checkbox)
    
    # Checkbox für IDENTITY-Variante
    identity_always_checkbox = QCheckBox("Manuelle IDs deaktivieren")
    identity_always_checkbox.setChecked(False)
    identity_always_checkbox.setToolTip("Unchecked: GENERATED BY DEFAULT (erlaubt manuelle ID-Eingabe)\nChecked: GENERATED ALWAYS (erzwingt nur automatische IDs)")
    options_layout.addWidget(identity_always_checkbox)
    
    # Checkbox für Collations
    step4_checkbox = QCheckBox("Collations ausführen")
    step4_checkbox.setChecked(True)
    step4_checkbox.setToolTip("Unchecked: Collations werden übersprungen\nChecked: Collations werden bei Migration und Flyway-Konvertierung ausgeführt")
    options_layout.addWidget(step4_checkbox)
    
    # Checkbox für Namen-Normalisierung (lowercase)
    normalize_columns_checkbox = QCheckBox("Namen zu lowercase normalisieren")
    normalize_columns_checkbox.setChecked(False)
    normalize_columns_checkbox.setToolTip("Konvertiert alle Tabellen- und Spaltennamen zu Kleinbuchstaben\n(z.B. firstName → firstname, MyTable → mytable)\nNötig für Hibernate-Kompatibilität mit PostgreSQL")
    options_layout.addWidget(normalize_columns_checkbox)
    
    options_layout.addStretch()
    db_layout.addLayout(options_layout)
    
    # Buttons zum Speichern/Laden und Testen
    btn_layout = QHBoxLayout()
    save_btn = QPushButton("💾 Konfiguration speichern")
    load_btn = QPushButton("📁 Konfiguration laden")
    import_btn = QPushButton("📥 Konfiguration importieren")
    import_btn.setToolTip("Importiere .env-Datei von einem anderen Ort")
    
    test_mssql_btn = QPushButton("🔌 MSSQL testen")
    test_mssql_btn.setStyleSheet("background-color: #0078D4; color: white;")
    
    test_pg_btn = QPushButton("🐘 PostgreSQL testen")
    test_pg_btn.setStyleSheet("background-color: #0078D4; color: white;")
    
    btn_layout.addWidget(save_btn)
    btn_layout.addWidget(load_btn)
    btn_layout.addWidget(import_btn)
    btn_layout.addWidget(test_mssql_btn)
    btn_layout.addWidget(test_pg_btn)
    btn_layout.addStretch()
    db_layout.addLayout(btn_layout)
    
    db_group.setLayout(db_layout)
    
    return db_group, {
        'mssql_server': mssql_server,
        'mssql_port': mssql_port,
        'mssql_database': mssql_database,
        'mssql_user': mssql_user,
        'mssql_password': mssql_password,
        'pg_host': pg_host,
        'pg_port': pg_port,
        'pg_database': pg_database,
        'pg_user': pg_user,
        'pg_password': pg_password,
        'log_level_combo': log_level_combo,
        'migrate_data_checkbox': migrate_data_checkbox,
        'identity_always_checkbox': identity_always_checkbox,
        'step4_checkbox': step4_checkbox,
        'normalize_columns_checkbox': normalize_columns_checkbox,
        'save_btn': save_btn,
        'load_btn': load_btn,
        'import_btn': import_btn,
        'test_mssql_btn': test_mssql_btn,
        'test_pg_btn': test_pg_btn,
    }


def build_migration_steps_section():
    """Baue Migrations-Schritte Sektion"""
    steps_group = QGroupBox("Migrationsschritte:")
    steps_layout = QVBoxLayout()
    
    # Einzelne Schritte
    step_buttons = QHBoxLayout()
    
    step1_btn = QPushButton("1️⃣ Tabellen & Daten")
    step2_btn = QPushButton("2️⃣ Verifizieren")
    step3_btn = QPushButton("3️⃣ Constraints & Indexes")
    step4_btn = QPushButton("4️⃣ Collations")
    
    step_buttons.addWidget(step1_btn)
    step_buttons.addWidget(step2_btn)
    step_buttons.addWidget(step3_btn)
    step_buttons.addWidget(step4_btn)
    
    steps_layout.addLayout(step_buttons)
    
    # Alle Schritte Button
    run_all_btn = QPushButton("ALLE SCHRITTE AUSFÜHREN")
    run_all_btn.setFont(QFont("Arial", 12, QFont.Weight.Bold))
    run_all_btn.setMinimumHeight(50)
    run_all_btn.setStyleSheet("""
        QPushButton {
            background-color: #2E7D32;
            color: white;
            border-radius: 5px;
        }
        QPushButton:hover {
            background-color: #388E3C;
        }
        QPushButton:disabled {
            background-color: #BDBDBD;
        }
    """)
    steps_layout.addWidget(run_all_btn)
    
    # Progress Bar
    progress = QProgressBar()
    progress.setTextVisible(True)
    steps_layout.addWidget(progress)
    
    steps_group.setLayout(steps_layout)
    
    return steps_group, {
        'step1_btn': step1_btn,
        'step2_btn': step2_btn,
        'step3_btn': step3_btn,
        'step4_btn': step4_btn,
        'run_all_btn': run_all_btn,
        'progress': progress,
    }


def build_log_section():
    """Baue Log-Sektion"""
    log_group = QGroupBox("Migration Log")
    log_layout = QVBoxLayout()
    
    log_output = QTextEdit()
    log_output.setReadOnly(True)
    log_output.setFont(QFont("Consolas", 9))
    log_output.setStyleSheet("background-color: #1E1E1E; color: #D4D4D4;")
    log_layout.addWidget(log_output)
    
    log_btn_layout = QHBoxLayout()
    clear_btn = QPushButton("🗑️ Migration-Logs löschen")
    save_log_btn = QPushButton("💾 Debug-Logs exportieren")
    view_mapping_btn = QPushButton("📋 Column Mapping anzeigen")
    collations_btn = QPushButton("⚙️ Collations konfigurieren")
    collations_btn.setToolTip("Öffne die collations_config.json Datei zum Bearbeiten")
    type_mappings_btn = QPushButton("🔄 Datentypen bearbeiten")
    type_mappings_btn.setToolTip("Bearbeite MSSQL → PostgreSQL Datentyp-Mappings")
    
    log_btn_layout.addWidget(clear_btn)
    log_btn_layout.addWidget(save_log_btn)
    log_btn_layout.addWidget(view_mapping_btn)
    log_btn_layout.addWidget(collations_btn)
    log_btn_layout.addWidget(type_mappings_btn)
    log_btn_layout.addStretch()
    log_layout.addLayout(log_btn_layout)
    
    log_group.setLayout(log_layout)
    
    return log_group, {
        'log_output': log_output,
        'clear_btn': clear_btn,
        'save_log_btn': save_log_btn,
        'view_mapping_btn': view_mapping_btn,
        'collations_btn': collations_btn,
        'type_mappings_btn': type_mappings_btn,
    }
